'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='cie6032-learning-v1';
const allQuestions=COURSE.flatMap(l=>l.quiz.map(q=>({...q,lesson:l.id})));
const qMap=Object.fromEntries(allQuestions.map(q=>[q.id,q]));
let state={version:1,last:'01',answers:{},mistakes:{},checks:{},notes:{},completed:{}};
let storageOK=true;
function validState(raw){
 if(!raw||raw.version!==1||typeof raw!=='object')throw Error('记录版本不匹配');
 const s={version:1,last:COURSE.some(l=>l.id===raw.last)?raw.last:'01',answers:{},mistakes:{},checks:{},notes:{},completed:{}};
 for(const q of allQuestions){const a=raw.answers?.[q.id];if(a&&Number.isInteger(a.choice)&&a.choice>=0&&a.choice<q.options.length)s.answers[q.id]={choice:a.choice,correct:a.choice===q.answer,attempts:Math.max(1,Math.min(9999,Number(a.attempts)||1))};if(raw.mistakes?.[q.id]===true)s.mistakes[q.id]=true;}
 for(const l of COURSE){s.notes[l.id]=typeof raw.notes?.[l.id]==='string'?raw.notes[l.id].slice(0,20000):'';s.checks[l.id]=Array.from({length:l.accept.length},(_,i)=>raw.checks?.[l.id]?.[i]===true);s.completed[l.id]=raw.completed?.[l.id]===true&&l.quiz.every(q=>s.answers[q.id]?.correct)&&s.checks[l.id].every(Boolean);}
 return s;
}
try{const raw=localStorage.getItem(KEY);if(raw)state=validState(JSON.parse(raw));}catch(e){storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}catch(e){storageOK=false;}$('#storage-warning').hidden=storageOK;}
$('#storage-warning').hidden=storageOK;
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3400);}
const lessonById=id=>COURSE.find(l=>l.id===id);
const correctCount=l=>l.quiz.filter(q=>state.answers[q.id]?.correct).length;
const doneCount=()=>COURSE.filter(l=>state.completed[l.id]).length;
const wrongQuestions=()=>allQuestions.filter(q=>state.answers[q.id]&&!state.answers[q.id].correct);
const uri=r=>encodeURI('../'+r.path)+(r.path.toLowerCase().endsWith('.pdf')?'#page='+r.page:'');
function refHTML(r){const ext=r.path.split('.').pop().toUpperCase();return `<a class="reference" href="${esc(uri(r))}" target="_blank" rel="noopener">${esc(r.label)} ↗<span>${ext}${ext==='PDF'?' · 原课程文件':''}</span></a>`;}
const linkLesson=(l,label='开始学习 →',cls='btn primary')=>`<a class="${cls}" href="#lesson/${l.id}">${label}</a>`;
function updateSide(){
 $('#lesson-nav').innerHTML=COURSE.map(l=>`<a href="#lesson/${l.id}" class="${location.hash===`#lesson/${l.id}`?'active':''}"><b class="${state.completed[l.id]?'done':''}">${state.completed[l.id]?'✓':l.id}</b><span>${esc(l.title)}</span></a>`).join('');
 $('#side-progress').textContent=`${doneCount()} / ${COURSE.length} 个模块完成`;
 $('#side-bar').style.width=doneCount()/COURSE.length*100+'%';
}
function header(kicker,title,desc,extra=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${extra}</div>`;}
function networkArt(){let lines='',nodes='';const cols=[3,5,5,2];const xs=[30,115,205,290];cols.forEach((count,c)=>{for(let i=0;i<count;i++){const y=95+(i-(count-1)/2)*33;if(c<3)for(let j=0;j<cols[c+1];j++){const yn=95+(j-(cols[c+1]-1)/2)*33;lines+=`<line x1="${xs[c]}" y1="${y}" x2="${xs[c+1]}" y2="${yn}" stroke="${i===1?'#b0a1ee':'#7882aa'}" stroke-opacity="${i===1?.45:.2}"/>`;}nodes+=`<circle cx="${xs[c]}" cy="${y}" r="${c===3?9:7}" fill="${c===3?'#c7dfa7':i===1?'#c0b1ff':'#626488'}"/>`;}});return `<svg viewBox="0 0 320 190" aria-hidden="true">${lines}${nodes}</svg><small>INPUT → REPRESENTATION → PREDICTION</small>`;}
function moduleCard(l){return `<article class="module-card"><div class="meta"><span>${l.id} / ${esc(l.week)}</span><span class="badge ${state.completed[l.id]?'green':''}">${state.completed[l.id]?'已完成':esc(l.phase)}</span></div><h3><a href="#lesson/${l.id}">${esc(l.title)}</a></h3><p>${esc(l.goal)}</p><footer><span>${correctCount(l)}/3 自测通过 · ${esc(l.time)}</span><a href="#lesson/${l.id}">进入 →</a></footer></article>`;}
function footer(){return '<div class="footer-note">基于本地 CIE6032 课件、13 组教程与 3 次作业编排。讲解与练习为学习辅助；课程要求以原文件为准。<br>记录保存在当前浏览器中，可导出备份。页面可离线使用；真实 Python / Notebook 实验需在相应环境中运行。</div>';}
function home(){
 const next=lessonById(state.last)||COURSE[0],answered=Object.keys(state.answers).length;
 return header('YOUR PERSONAL LEARNING SPACE','把深度学习，真正学会。','从数学直觉到代码实践，沿着一条有证据的学习路径前进。','<span class="subtle">CIE6032 · 2026 COURSE</span>')+`<section class="hero"><div><div class="eyebrow">${answered?'CONTINUE YOUR JOURNEY':'START WITH THE FOUNDATIONS'}</div><h2>${answered?esc(next.title):'看懂原理，亲手验证，<br>再用自己的话解释。'}</h2><p>15 个学习模块，连接原始课件、课堂教程与作业。每次学习完成一个小闭环，而不只是多看几页幻灯片。</p><div style="display:flex;gap:10px;flex-wrap:wrap">${linkLesson(next,answered?'继续学习 →':'从第 01 课开始 →','btn light')}<a class="btn ghost" href="#diagnostic">做一次起点自测</a></div></div><div class="hero-art">${networkArt()}</div></section>
 <div class="feature-links"><a href="#depth/03">∂ 分步推导与 PyTorch</a><a href="#coverage">▤ 课件逐页索引</a><a href="#evidence">↗ 本机真实实验</a><a href="#plan">◎ 算法与 LLM 路线</a></div><div class="stats"><div class="stat"><div><div class="number">${doneCount()}<span style="font-size:14px;color:var(--muted)"> / 15</span></div><small>完成的学习模块</small></div><span class="symbol">✓</span></div><div class="stat"><div><div class="number">${answered}<span style="font-size:14px;color:var(--muted)"> / 45</span></div><small>已尝试自测题</small></div><span class="symbol">?</span></div><div class="stat"><div><div class="number">${wrongQuestions().length}</div><small>当前待复习错题</small></div><span class="symbol">↻</span></div><div class="stat"><div><div class="number">${Object.keys(LABS).length}</div><small>浏览器互动实验</small></div><span class="symbol">◈</span></div></div>
 <div class="dashboard-grid"><section><div class="section-head"><h2>推荐学习路线</h2><a class="subtle" href="#roadmap">查看全部 15 课 →</a></div><div class="panel route-list">${[['01','01 — 03 · 学习的基本语言','数据、张量、交叉熵与反向传播'],['04','04 — 06 · 从网络到可训练的模型','CNN、残差与优化诊断'],['07','07 — 09 · 序列与注意力','RNN、Transformer 与 ViT'],['10','10 — 14 · 生成与视觉任务','GAN、Diffusion、检测、分割与图像梯度'],['15','15 · 用实验连接所有知识','基线、控制变量、复现与报告']].map(([id,t,d],i)=>`<div class="route-item"><div class="route-num">0${i+1}</div><div class="route-text"><h3>${t}</h3><p>${d}</p></div><a href="#lesson/${id}">进入 ↗</a></div>`).join('')}</div></section><aside><div class="section-head"><h2>今天，动手做一件事</h2></div><div class="practice-card"><div class="eyebrow">LEARNING BY DOING</div><h3>学习率变大后，<br>一定学得更快吗？</h3><p>调节步长，观察参数是收敛、震荡还是发散。先预测结果，再运行实验。</p><div class="mini-grid" aria-hidden="true">${'<span></span>'.repeat(21)}</div><a class="btn" href="#lab/gradient">打开梯度下降实验 ↗</a></div><div class="tip"><strong>建议每次学习 45–90 分钟</strong>读一段讲解，算一个例子，完成一个实验。把无法解释的地方写进笔记，再回来补齐。</div></aside></div>`+footer();
}
let phaseFilter='全部';
function roadmap(){const phases=['全部',...new Set(COURSE.map(l=>l.phase))];return header('CURRICULUM','从基础到独立实验','按依赖顺序学习；已熟悉的主题可先自测，再决定是否深入。')+`<div class="filters" aria-label="按主题筛选">${phases.map(p=>`<button data-phase="${p}" class="${p===phaseFilter?'active':''}" aria-pressed="${p===phaseFilter}">${p}</button>`).join('')}</div><div class="cards">${COURSE.filter(l=>phaseFilter==='全部'||l.phase===phaseFilter).map(moduleCard).join('')}</div>`+footer();}
function quizHTML(q){const a=state.answers[q.id];return `<form class="quiz" data-question="${q.id}"><fieldset><legend>${esc(q.prompt)}</legend><div class="quiz-options">${q.options.map((o,i)=>`<label class="choice"><input type="radio" name="q-${q.id}" value="${i}" ${a?.choice===i?'checked':''} required><span>${String.fromCharCode(65+i)}. ${esc(o)}</span></label>`).join('')}</div></fieldset><div class="quiz-actions"><button class="btn small ${a?'':'primary'}" type="submit">${a?'重新检查':'检查答案'}</button>${a?`<span class="subtle">已尝试 ${a.attempts} 次</span>`:''}</div>${a?`<div class="feedback ${a.correct?'':'wrong'}" role="status"><strong>${a.correct?'回答正确。':'还需要再想一想。'}</strong> ${esc(q.why)}${a.correct?'':`<br>正确选项：${esc(q.options[q.answer])}`}</div>`:''}</form>`;}
function eligible(l){return l.quiz.every(q=>state.answers[q.id]?.correct)&&l.accept.every((_,i)=>state.checks[l.id]?.[i]);}
function finishButton(l){return `<button class="btn ${state.completed[l.id]?'success':'primary'}" id="complete-lesson" data-lesson="${l.id}" ${!eligible(l)?'disabled':''}>${state.completed[l.id]?'✓ 本模块已完成':'记录本模块完成'}</button>`;}
function lesson(id){const l=lessonById(id);if(!l)return '<div class="empty">没有找到这节课。<a href="#roadmap">返回课程路线</a></div>';state.last=id;save();
 return `<div class="lesson-hero"><div class="eyebrow">MODULE ${id} / 15 · ${esc(l.week)}</div><h1>${esc(l.title)}</h1><div class="en">${esc(l.en)}</div><div class="lesson-meta"><span class="badge">${esc(l.phase)}</span><span class="badge muted">${esc(l.time)}</span><span class="badge muted">自测 <span id="lesson-score">${correctCount(l)}</span>/3</span></div><div class="goal"><strong>这一课要能做到</strong>${esc(l.goal)}</div><div class="subtle">前置知识：${esc(l.prereq)}</div><div class="flow" aria-label="本课主流程">${l.chain.map((s,i)=>`${i?'<i aria-hidden="true">→</i>':''}<span>${esc(s)}</span>`).join('')}</div></div>
 <div class="lesson-layout"><article class="lesson-body">${l.concepts.map((c,i)=>`<section class="concept"><h2><span class="concept-index">0${i+1}</span>${esc(c.title)}</h2><p>${esc(c.body)}</p></section>`).join('')}<section class="formula"><div class="eyebrow">KEEP THESE RELATIONSHIPS</div><pre>${esc(l.formula)}</pre></section><div class="callout"><strong>一起算一个例子</strong>${esc(l.worked)}</div>${depthHTML(l)}<div class="callout warning"><strong>容易踩的坑</strong>${esc(l.pitfall)}</div>${l.lab?labHTML(l.lab):''}<section class="panel" style="margin-top:25px"><div class="eyebrow">PRACTICE · TRANSFER TO YOUR COURSE</div><h2 style="font-size:19px">把原理带回实际代码</h2><ol class="task-list">${l.practice.map(p=>`<li>${esc(p)}</li>`).join('')}</ol>${l.download?`<a class="btn" href="${esc(l.download)}" download>下载${l.download.endsWith('.py')?'配套 Python 实验':'实验记录模板'} ↓</a>`:''}<p class="notebook-note">练习请在原 Notebook 的复制件中完成，保留原课程材料。本站不执行 Python，也不自动下载数据或模型；附带 CPU 实验说明见实验室。</p></section><div class="section-head"><h2>检查理解，再继续</h2><small>每题独立判断 · 答后查看解析</small></div>${l.quiz.map(quizHTML).join('')}<section class="panel" style="margin-top:22px"><div class="eyebrow">EXPLAIN IT IN YOUR OWN WORDS</div><h2 style="font-size:18px">完成标准</h2><p class="subtle">勾选代表你的自我确认；不是自动评分。三题答对且完成以下任务后，可记录本模块完成。</p><div class="checks">${l.accept.map((t,i)=>`<label class="check"><input type="checkbox" data-check="${l.id}/${i}" ${state.checks[l.id]?.[i]?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div><div id="completion-holder">${finishButton(l)}</div></section><section style="margin-top:28px"><div class="section-head"><h2>我的复述与疑问</h2><small>自动保存在当前浏览器</small></div><textarea class="note" data-note="${l.id}" maxlength="20000" aria-label="第 ${l.id} 课学习笔记" placeholder="试着不用课件，用自己的话解释主流程。哪里还无法独立推导？实验观察到了什么？">${esc(state.notes[l.id]||'')}</textarea><div class="save-status" id="note-status">建议记录：我的理解 / 证据与输出 / 仍待验证的问题。</div></section><div class="lesson-footer">${Number(id)>1?linkLesson(COURSE[Number(id)-2],'← 上一课','btn'):'<a class="btn" href="#roadmap">← 课程路线</a>'}${Number(id)<15?linkLesson(COURSE[Number(id)],'下一课 →','btn'):linkLesson(COURSE[0],'返回基础复盘 ↻','btn')}</div></article><aside class="lesson-side"><section class="panel"><h3>本课原始材料</h3>${l.refs.map(refHTML).join('')}<p class="notebook-note">PDF 可直接阅读；IPYNB 需在 Jupyter 或 Colab 打开。源码链接可能直接显示文本或下载。</p></section><section class="panel"><h3>学习时问自己</h3><p class="subtle">输入和输出是什么？<br>关键张量形状如何变化？<br>梯度沿哪条路径传播？<br>怎样设计一个小实验验证？</p><a class="btn small" href="#review">查看待复习题 ↻</a></section></aside></div>`+footer();}
const LABS={split:{title:'混淆矩阵与评价指标',desc:'调整 TP、FP、FN、TN，观察同一预测在不同指标下的含义。',lesson:'01'},gradient:{title:'梯度下降：步长与稳定性',desc:'在 L(w)=½aw² 上计算真实迭代，观察收敛、震荡与发散。',lesson:'06'},softmax:{title:'Softmax 与交叉熵',desc:'改变 logits，查看概率、损失以及对 logits 的梯度。',lesson:'03'},convolution:{title:'卷积滑窗：一次乘加',desc:'在固定 5×5 输入上逐格滑动 3×3 核，拆解输出的来源。',lesson:'04'},attention:{title:'注意力：匹配、屏蔽与聚合',desc:'切换 query 和因果 mask，观察每行权重如何重新归一化。',lesson:'08'},patches:{title:'ViT：patch 大小与计算代价',desc:'同样的图像，为什么切得更细会显著增加注意力开销？',lesson:'09'},diffusion:{title:'扩散模型：前向加噪',desc:'固定一个噪声样本，观察信号和噪声的相对强度。此处不运行去噪网络。',lesson:'11'},iou:{title:'IoU：几何重叠的尺度',desc:'移动预测框，观察交集、并集以及交并比。',lesson:'12'}};
Object.assign(LABS,EXTRA_LABS);
function range(name,label,min,max,value,step=1){return `<label class="control">${label}<input type="range" data-param="${name}" min="${min}" max="${max}" value="${value}" step="${step}" aria-label="${label}"></label>`;}
function select(name,label,items){return `<label class="control">${label}<select data-param="${name}">${items.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;}
function labHTML(kind){const l=LABS[kind];if(!l)return '';let c=EXTRA_LABS[kind]?extraControls(kind):'';
 if(kind==='split')c=range('tp','真正例 TP',0,100,6)+range('fp','假正例 FP',0,100,2)+range('fn','假负例 FN',0,100,4)+range('tn','真负例 TN',0,100,88);
 if(kind==='gradient')c=range('eta','学习率 η',.01,1.5,.15,.01)+range('a','曲率 a',.5,4,2,.1);
 if(kind==='softmax')c=range('z0','类别 A · logit',-6,6,1,.1)+range('z1','类别 B · logit',-6,6,0,.1)+range('z2','类别 C · logit',-6,6,-1,.1)+select('target','正确类别',[[0,'A'],[1,'B'],[2,'C']]);
 if(kind==='convolution')c=range('pos','滑窗位置（0–8）',0,8,0)+select('kernel','卷积核',[[0,'水平差分核'],[1,'均值核（1/9）']]);
 if(kind==='attention')c=select('query','当前 query',[[0,'我'],[1,'正在'],[2,'学习'],[3,'深度学习']])+select('mask','可见范围',[[0,'双向：所有 token'],[1,'因果：当前位置及以前']])+range('temperature','额外温度 τ（在 √dₖ 缩放之后）',.2,2,1,.1);
 if(kind==='patches')c=select('patch','Patch 边长 P',[[16,'16 px'],[8,'8 px'],[32,'32 px']]);
 if(kind==='diffusion')c=range('alpha','累计信号方差比例 ᾱ',0,1,.81,.01);
 if(kind==='iou')c=range('x','预测框左上角 x',0,180,100)+range('y','预测框左上角 y',0,130,70);
 return `<section class="lab" data-lab="${kind}"><div class="eyebrow">INTERACTIVE LAB</div><h3>${l.title}</h3><p class="subtle">${l.desc}</p><div class="lab-controls">${c}</div><div class="lab-visual" aria-label="${l.title}可视化"></div><div class="lab-result" aria-live="polite"></div></section>`;
}
function softmax(xs){const m=Math.max(...xs),es=xs.map(x=>Math.exp(x-m)),s=es.reduce((a,b)=>a+b,0);return es.map(x=>x/s);}
function matrix(vals,cols,hot=()=>false,selected=()=>false){return `<div class="matrix" style="grid-template-columns:repeat(${cols},1fr)">${vals.map((v,i)=>`<span class="cell ${hot(i)?'hot':''} ${selected(i)?'selected':''}">${typeof v==='number'?(Number.isInteger(v)?v:v.toFixed(2)):v}</span>`).join('')}</div>`;}
function updateLab(el){const kind=el.dataset.lab,params=Object.fromEntries([...el.querySelectorAll('[data-param]')].map(x=>[x.dataset.param,Number(x.value)])),visual=el.querySelector('.lab-visual'),result=el.querySelector('.lab-result');if(EXTRA_LABS[kind]){updateExtraLab(el,kind,params);return;}let html='',out='';
 if(kind==='split'){const{tp,fp,fn,tn}=params,total=tp+fp+fn+tn;const fmt=(a,b)=>b?(100*a/b).toFixed(1)+'%':'未定义（分母为 0）';html=`<div class="matrix-row"><div><div class="matrix-label">行：实际正/负；列：预测正/负</div>${matrix([`TP ${tp}`,`FN ${fn}`,`FP ${fp}`,`TN ${tn}`],2,i=>i===0||i===3)}</div></div>`;out=`N=${total} · Accuracy=${fmt(tp+tn,total)}<br>Precision=${fmt(tp,tp+fp)} · Recall=${fmt(tp,tp+fn)} · F1=${fmt(2*tp,2*tp+fp+fn)}<br>分母为 0 时不在这里擅自设为 0；实际评价应明确处理约定。`;}
 if(kind==='gradient'){const{eta,a}=params;let w=3,ws=[w];for(let i=0;i<24;i++){w*=1-eta*a;ws.push(w);}const max=Math.max(3,Math.min(12,Math.max(...ws.map(Math.abs)))),y=v=>120-Math.max(-max,Math.min(max,v))/max*88;const points=ws.map((v,i)=>`${40+i*18.5},${y(v).toFixed(2)}`).join(' ');html=`<svg viewBox="0 0 520 250" role="img" aria-label="24 步参数 w 的变化，横轴迭代次数，纵轴参数值"><line class="graph-axis" x1="40" y1="120" x2="490" y2="120"/><line class="graph-axis" x1="40" y1="25" x2="40" y2="215"/><text class="chart-label" x="10" y="30">w</text><text class="chart-label" x="6" y="123">0</text><text class="chart-label" x="9" y="40">${max.toFixed(0)}</text><text class="chart-label" x="9" y="211">−${max.toFixed(0)}</text><text class="chart-label" x="35" y="239">0</text><text class="chart-label" x="470" y="239">24 步</text><polyline points="${points}" fill="none" stroke="#7562dd" stroke-width="2.5"/>${ws.map((v,i)=>`<circle cx="${40+i*18.5}" cy="${y(v)}" r="3" fill="#7562dd"/>`).join('')}</svg>`;const r=Math.abs(1-eta*a),status=r<1?'收敛':Math.abs(r-1)<1e-10?'临界：不衰减':'发散';out=`η=${eta.toFixed(2)}，a=${a.toFixed(1)}，每步乘数 1−ηa=${(1-eta*a).toFixed(3)} → <strong>${status}</strong><br>w₀=3，w₂₄=${Math.abs(w)>1e4?w.toExponential(3):w.toFixed(6)}。稳定需要 0&lt;ηa&lt;2。${Math.max(...ws.map(Math.abs))>12?'图中超出 ±12 的值已截断显示；数值仍为真实迭代结果。':''}`;}
 if(kind==='softmax'){const z=[params.z0,params.z1,params.z2],p=softmax(z),y=params.target;html=p.map((v,i)=>`<div class="bar-row"><span>类别 ${'ABC'[i]}${i===y?' ✓':''}</span><div class="bar-track"><div class="bar-fill ${i===y?'target':''}" style="width:${v*100}%"></div></div><span>${v.toFixed(4)}</span></div>`).join('');out=`logits=[${z.map(v=>v.toFixed(1)).join(', ')}] · 正确类别=${'ABC'[y]}<br>CE=−ln pᵧ=${(-Math.log(p[y])).toFixed(4)}<br>∂L/∂logits=[${p.map((v,i)=>(v-(i===y?1:0)).toFixed(4)).join(', ')}]；所有梯度之和≈0。`;}
 if(kind==='convolution'){const data=[0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1,0,0,1,1,1],k=params.kernel===0?[-1,0,1,-1,0,1,-1,0,1]:Array(9).fill(1/9),r=Math.floor(params.pos/3),c=params.pos%3;const outputs=Array.from({length:9},(_,p)=>{const rr=Math.floor(p/3),cc=p%3;return k.reduce((s,v,i)=>s+v*data[(rr+Math.floor(i/3))*5+cc+i%3],0);});html=`<div class="matrix-row"><div><div class="matrix-label">输入 5×5 · 高亮当前窗口</div>${matrix(data,5,i=>Math.floor(i/5)>=r&&Math.floor(i/5)<r+3&&i%5>=c&&i%5<c+3)}</div><div><div class="matrix-label">核 3×3</div>${matrix(k,3)}</div><div><div class="matrix-label">输出 3×3</div>${matrix(outputs,3,()=>false,i=>i===params.pos)}</div></div>`;out=`stride=1，padding=0；当前位置 (row=${r}, col=${c})<br>${k.map((v,i)=>`${data[(r+Math.floor(i/3))*5+c+i%3]}×${params.kernel===1?'1/9':v}`).join(' + ')} = <strong>${outputs[params.pos].toFixed(3)}</strong><br>采用不翻核的互相关约定。均值核不是可学习示例，只用于观察局部平滑。`;}
 if(kind==='attention'){const tokens=['我','正在','学习','深度学习'],vec=[[1,0],[0,1],[1,1],[2,1]],values=[1,2,4,8],qi=params.query,q=vec[qi],logits=vec.map((k,j)=>params.mask&&j>qi?-Infinity:(q[0]*k[0]+q[1]*k[1])/Math.sqrt(2)/params.temperature),p=softmax(logits);html=p.map((v,i)=>`<div class="bar-row"><span>${tokens[i]}</span><div class="bar-track"><div class="bar-fill" style="width:${v*100}%"></div></div><span>${v.toFixed(3)}</span></div>`).join('');out=`玩具例子：Q、K 的向量相同且 dₖ=2；不是预训练语言模型。<br>query「${tokens[qi]}」=[${q}]；V=[1,2,4,8]；τ=${params.temperature.toFixed(1)}<br>权重和=${p.reduce((a,b)=>a+b,0).toFixed(3)}；输出 Σaⱼvⱼ=<strong>${p.reduce((s,v,i)=>s+v*values[i],0).toFixed(3)}</strong>。${params.mask?'未来 key 的权重为 0。':'当前允许读取所有 token。'}`;}
 if(kind==='patches'){const p=params.patch,n=224/p,t=n*n+1,spacing=224/n;let lines='';for(let i=1;i<n;i++)lines+=`<path d="M${36+i*spacing} 12V236 M36 ${12+i*spacing}H260" stroke="#fff" stroke-opacity=".7" stroke-width="1"/>`;html=`<svg viewBox="0 0 420 250" role="img" aria-label="224 像素图像的 patch 网格"><defs><linearGradient id="patch-gradient" x2="1" y2="1"><stop stop-color="#8574d8"/><stop offset="1" stop-color="#b8d2a1"/></linearGradient></defs><rect x="36" y="12" width="224" height="224" rx="2" fill="url(#patch-gradient)"/>${lines}<text x="278" y="80" class="chart-value">${n} × ${n} patches</text><text x="278" y="110" class="chart-label">每块 ${p} × ${p} px</text><text x="278" y="140" class="chart-label">RGB → ${3*p*p} 维</text><text x="278" y="170" class="chart-label">+ 1 class token</text></svg>`;out=`N=${n*n}，T=${t}；每个 head 的注意力分数矩阵为 ${t}×${t}=<strong>${(t*t).toLocaleString()}</strong> 个元素。<br>这是分数矩阵的元素数量，不是整个模型的 FLOPs 或总显存。`;}
 if(kind==='diffusion'){html='<canvas class="noise-canvas" width="28" height="28" role="img" aria-label="固定玩具图案在当前信号强度下的加噪结果"></canvas>';const alpha=params.alpha;out=`ᾱ=${alpha.toFixed(2)} · 信号系数 √ᾱ=${Math.sqrt(alpha).toFixed(3)} · 噪声系数 √(1−ᾱ)=${Math.sqrt(1-alpha).toFixed(3)}<br>xₜ=√ᾱ x₀+√(1−ᾱ)ε；固定同一 ε 比较不同边际噪声水平。<br>仅显示已知前向过程；不是完整 Markov 轨迹，也不是训练好的图像生成器。显示时将值裁剪到 [−1,1] 后映射为灰度。`;}
 if(kind==='iou'){const{x,y}=params,ax=60,ay=45,aw=100,ah=80,bw=100,bh=80,ix=Math.max(ax,x),iy=Math.max(ay,y),iw=Math.max(0,Math.min(ax+aw,x+bw)-ix),ih=Math.max(0,Math.min(ay+ah,y+bh)-iy),inter=iw*ih,union=16000-inter;html=`<svg viewBox="0 0 310 230" role="img" aria-label="真实框与预测框的重叠区域"><rect x="${ax}" y="${ay}" width="${aw}" height="${ah}" rx="2" fill="#759eb0" fill-opacity=".18" stroke="#498397" stroke-width="2"/><rect x="${x}" y="${y}" width="100" height="80" rx="2" fill="#8d7be3" fill-opacity=".2" stroke="#7561cf" stroke-width="2"/>${inter?`<rect x="${ix}" y="${iy}" width="${iw}" height="${ih}" fill="#8d7be3" fill-opacity=".45"/>`:''}<text class="chart-label" x="65" y="38">真实框 A</text><text class="chart-label" x="${x+5}" y="${y+94}">预测框 B</text></svg>`;out=`A=[60,45,160,125]；B=[${x},${y},${x+100},${y+80}]<br>交集=${inter}，并集=${union}；<strong>IoU=${(inter/union).toFixed(4)}</strong>。坐标采用连续空间定义。`;}
 visual.innerHTML=html;result.innerHTML=out;
 if(kind==='diffusion'){const canvas=visual.querySelector('canvas'),ctx=canvas.getContext('2d'),img=ctx.createImageData(28,28);let seed=42;const rng=()=>{seed=(1664525*seed+1013904223)>>>0;return(seed+1)/4294967297;};for(let y=0;y<28;y++)for(let x=0;x<28;x++){const d=Math.hypot(x-13.5,y-13.5),clean=(d>6&&d<10)||(x>11&&x<16&&y>5&&y<23)?1:-1,noise=Math.sqrt(-2*Math.log(rng()))*Math.cos(2*Math.PI*rng()),v=Math.sqrt(params.alpha)*clean+Math.sqrt(1-params.alpha)*noise,byte=Math.round((Math.max(-1,Math.min(1,v))+1)*127.5),i=(y*28+x)*4;img.data[i]=img.data[i+1]=img.data[i+2]=byte;img.data[i+3]=255;}ctx.putImageData(img,0,0);}
}
function labs(){return header('EXPLORE BY CHANGING ONE THING','互动实验室','先做预测，再改变参数。所有示意在浏览器本地计算，不需要 GPU。')+`<div class="cards">${Object.entries(LABS).map(([id,l],i)=>`<article class="module-card"><div class="meta"><span>LAB ${String(i+1).padStart(2,'0')}</span><span class="badge">浏览器内运行</span></div><h3>${l.title}</h3><p>${l.desc}</p><footer><a href="#lesson/${l.lesson}">对应第 ${l.lesson} 课</a><a href="#lab/${id}">开始实验 →</a></footer></article>`).join('')}</div><div class="section-head"><h2>从示意走到真实代码</h2></div><div class="panel"><p class="subtle">附带 4 个独立练习脚本。gradient_check.py 只使用 Python 标准库；其余需要本地安装 PyTorch。CPU 即可运行，不下载数据集。真实运行结果由脚本输出，页面不会伪造训练曲线。</p><div class="storage-controls">${[['gradient_check.py','数值梯度检查'],['mlp_cpu.py','CPU MLP 训练'],['tensor_shapes.py','CNN 与残差形状'],['attention_cpu.py','因果注意力检查']].map(([p,t])=>`<a class="btn" href="labs/${p}" download>${t} ↓</a>`).join('')}<a class="btn" href="labs/README.md" target="_blank">运行说明 ↗</a></div></div>`+footer();}
const diagnosticIds=['01a','02c','03a','04a','06a','08a','10a','11b'];
function diagnostic(){const qs=diagnosticIds.map(id=>qMap[id]),tried=qs.filter(q=>state.answers[q.id]).length,correct=qs.filter(q=>state.answers[q.id]?.correct).length;const weak=[...new Set(qs.filter(q=>state.answers[q.id]&&!state.answers[q.id].correct).map(q=>q.lesson))];return header('FIND YOUR STARTING POINT','先找起点，不急着刷进度','8 道题覆盖基础、网络与生成模型；结果用于安排复习，不代表整门课的能力评级。')+`<div class="diagnostic-head">建议独立作答，不查材料。答题记录会同步到对应课程。看过解析后的答对用于练习记录，不能当作独立测评成绩。</div><div class="result-summary" id="diagnostic-summary">已作答 ${tried}/8，当前答对 ${correct}/8。${weak.length?'<br>建议回看：'+weak.map(id=>`<a href="#lesson/${id}">第 ${id} 课</a>`).join(' · '):'<br>完成后，根据错题进入相应模块。'}</div>${qs.map(quizHTML).join('')}`+footer();}
let reviewAll=false;
function review(){const qs=reviewAll?allQuestions.filter(q=>state.mistakes[q.id]):wrongQuestions();return header('RECALL · CHECK · REVISIT','让错题变成下一次理解','重新作答后会更新当前状态；历史错误仍保留，方便间隔复习。','<a class="btn" href="#diagnostic">起点自测</a>')+`<div class="filters"><button data-review="current" class="${!reviewAll?'active':''}">当前错题 (${wrongQuestions().length})</button><button data-review="all" class="${reviewAll?'active':''}">历史错题 (${Object.keys(state.mistakes).length})</button></div>${qs.length?qs.map(q=>`<div class="section-head"><a href="#lesson/${q.lesson}">第 ${q.lesson} 课 · ${esc(lessonById(q.lesson).title)} ↗</a>${state.answers[q.id]?.correct?'<span class="badge green">最近已答对</span>':''}</div>${quizHTML(q)}`).join(''):'<div class="empty">这里暂时没有错题。<br>可以先做起点自测，或从每节课的理解题开始。<br><a class="btn primary" style="margin-top:15px" href="#diagnostic">开始 8 题自测 →</a></div>'}`+footer();}
function resources(){return header('YOUR COURSE MATERIALS','把讲解与原始证据放在一起','每个模块都可回到课件、Notebook 与作业源码。所有课程链接指向整理后的本地文件。')+`<div class="resources-grid">${COURSE.map(l=>`<section class="panel"><div class="eyebrow">MODULE ${l.id}</div><h3>${esc(l.title)}</h3>${l.refs.map(refHTML).join('')}</section>`).join('')}<section class="panel"><div class="eyebrow">BOOKS & REVIEW</div><h3>教材与复习速查</h3>${[R('动手学深度学习 · 中文','Textbooks/d2l-zh.pdf'),R('Dive into Deep Learning · English','Textbooks/d2l-en.pdf'),R('Deep Learning · Goodfellow','Textbooks/Deep+Learning+Ian+Goodfellow.pdf'),R('速查笔记 1','Review/CheatSheets/1.pdf'),R('速查笔记 2','Review/CheatSheets/2.pdf')].map(refHTML).join('')}</section></div><p class="notebook-note">本站不会把 IPYNB 当成已执行代码。请在 Jupyter / Colab 中打开 Notebook，并检查环境、路径和下载需求。PDF 首次打开通常从第一页开始，由原目录定位进一步阅读。</p>`+footer();}
function notes(){const withNotes=COURSE.filter(l=>(state.notes[l.id]||'').trim());return header('CAPTURE YOUR UNDERSTANDING','留下你自己的解释','笔记与进度仅存储在当前浏览器；切换浏览器或移动页面前，建议先导出。')+`<div class="storage-controls"><button class="btn primary" data-export>导出全部学习记录 ↓</button><button class="btn" data-import>导入学习记录 ↑</button><a class="btn" href="labs/experiment_template.md" download>实验记录模板 ↓</a></div><p class="subtle">导入会用文件中的记录替换当前记录；导入前会再次确认。导出内容包含进度、自测、错题及笔记，不包含任何课程文件。</p>${withNotes.length?withNotes.map(l=>`<section class="panel" style="margin-top:20px"><div class="section-head" style="margin-top:0"><h2><a href="#lesson/${l.id}">${l.id} · ${esc(l.title)}</a></h2></div><textarea class="note" data-note="${l.id}" maxlength="20000" aria-label="${esc(l.title)}笔记">${esc(state.notes[l.id])}</textarea></section>`).join(''):'<div class="empty" style="margin-top:25px">还没有学习笔记。每一课底部都可以记录自己的推导、实验现象和疑问。<br><a href="#lesson/01">从第一课开始 →</a></div>'}`+footer();}
function searchPage(term){const t=term.toLocaleLowerCase(),ls=COURSE.filter(l=>[l.title,l.en,l.goal,l.formula,l.pitfall,...l.concepts.map(c=>c.title+' '+c.body),...l.practice,l.depth?.title,l.depth?.torch,...(l.depth?.steps||[]).flat(),...l.refs.map(r=>r.label)].join(' ').toLocaleLowerCase().includes(t));return header('SEARCH THE COURSE','找到一个知识点','搜索包含中英文主题、公式、讲解和实践路线。')+`<p class="search-count">“${esc(term)}” · ${ls.length} 个相关模块</p><div class="cards">${ls.map(moduleCard).join('')}</div>${ls.length?'':'<div class="empty">没有匹配结果。试试“梯度”“Attention”“卷积”或“mask”。</div>'}`;}
function closeMenu(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show');$('#menu-toggle').setAttribute('aria-expanded','false');}
function route(){let hash=location.hash.slice(1)||'home';let [view,arg]=hash.split('/');try{arg=decodeURIComponent(hash.slice(view.length+1));}catch(e){arg='';}const titles={home:'总览',roadmap:'课程路线',labs:'互动实验室',lab:'互动实验',lesson:'模块学习',review:'自测与错题',diagnostic:'起点自测',resources:'课程资料',notes:'学习笔记',search:'搜索',depth:'推导与 PyTorch',coverage:'课件覆盖',plan:'学习与算力',evidence:'真实实验'};let html;
 if(view==='depth')html=depthPage(arg);else if(view==='coverage')html=coveragePage();else if(view==='plan')html=planPage();else if(view==='evidence')html=evidencePage();else if(view==='home')html=home();else if(view==='roadmap')html=roadmap();else if(view==='lesson')html=lesson(arg);else if(view==='labs')html=labs();else if(view==='lab')html=LABS[arg]?header('INTERACTIVE LAB',LABS[arg].title,LABS[arg].desc,`<a class="btn" href="#lesson/${LABS[arg].lesson}">回到课程 →</a>`)+labHTML(arg)+footer():'<div class="empty">实验不存在。<a href="#labs">返回实验室</a></div>';else if(view==='review')html=review();else if(view==='diagnostic')html=diagnostic();else if(view==='resources')html=resources();else if(view==='notes')html=notes();else if(view==='search')html=searchPage(arg.slice(0,100));else html=home();
 $('#main').innerHTML=html;$('#breadcrumb').textContent=titles[view]||'总览';document.title=(view==='lesson'&&lessonById(arg)?lessonById(arg).title:titles[view]||'总览')+' · CIE6032';$$('[data-nav]').forEach(a=>{const active=a.dataset.nav===view||(a.dataset.nav==='labs'&&view==='lab')||(a.dataset.nav==='review'&&view==='diagnostic');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});updateSide();$$('[data-lab]').forEach(updateLab);closeMenu();window.scrollTo(0,0);$('#main').focus({preventScroll:true});
}
function updateLessonProgress(){const l=lessonById(location.hash.split('/')[1]);if(l&&$('#completion-holder')){$('#completion-holder').innerHTML=finishButton(l);$('#lesson-score').textContent=correctCount(l);}updateSide();}
document.addEventListener('submit',e=>{
 if(e.target.id==='search-form'){e.preventDefault();const term=$('#search').value.trim();if(term)location.hash='search/'+encodeURIComponent(term);return;}
 const form=e.target.closest('[data-question]');if(!form)return;e.preventDefault();const checked=form.querySelector('input:checked');if(!checked)return;const q=qMap[form.dataset.question],choice=Number(checked.value),correct=choice===q.answer;state.answers[q.id]={choice,correct,attempts:(state.answers[q.id]?.attempts||0)+1};if(!correct){state.mistakes[q.id]=true;state.completed[q.lesson]=false;}save();form.outerHTML=quizHTML(q);updateLessonProgress();if($('#diagnostic-summary')){const qs=diagnosticIds.map(id=>qMap[id]),weak=[...new Set(qs.filter(x=>state.answers[x.id]&&!state.answers[x.id].correct).map(x=>x.lesson))];$('#diagnostic-summary').innerHTML=`已作答 ${qs.filter(x=>state.answers[x.id]).length}/8，当前答对 ${qs.filter(x=>state.answers[x.id]?.correct).length}/8。${weak.length?'<br>建议回看：'+weak.map(id=>`<a href="#lesson/${id}">第 ${id} 课</a>`).join(' · '):'<br>建议继续用独立推导与实践验证理解。'}`;}
});
document.addEventListener('input',e=>{const t=e.target;if(t.matches('[data-param]'))updateLab(t.closest('[data-lab]'));if(t.matches('[data-note]')){state.notes[t.dataset.note]=t.value.slice(0,20000);save();if($('#note-status'))$('#note-status').textContent=storageOK?'已保存到当前浏览器。':'暂存于本次打开，请导出备份。';}});
document.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-check]')){const[id,index]=t.dataset.check.split('/');state.checks[id]??=[];state.checks[id][Number(index)]=t.checked;if(!t.checked)state.completed[id]=false;save();updateLessonProgress();}});
document.addEventListener('click',e=>{const phase=e.target.closest('[data-phase]');if(phase){phaseFilter=phase.dataset.phase;route();}const rev=e.target.closest('[data-review]');if(rev){reviewAll=rev.dataset.review==='all';route();}const complete=e.target.closest('#complete-lesson');if(complete){const l=lessonById(complete.dataset.lesson);if(eligible(l)){state.completed[l.id]=true;save();updateLessonProgress();toast('已记录完成。建议隔几天再独立复述一次。');}}if(e.target.closest('[data-export]'))exportState();if(e.target.closest('[data-import]'))$('#import-file').click();});
function exportState(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='cie6032-learning-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('学习记录已导出。');}
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>2000000)throw Error('文件过大（上限 2 MB）');const parsed=validState(JSON.parse(await file.text()));if(!confirm('导入将替换当前的学习进度、答题与笔记。已备份当前记录并继续？'))return;state=parsed;save();route();toast('学习记录已导入。');}catch(error){toast('无法导入：'+error.message);}});
$('#menu-toggle').addEventListener('click',()=>{const open=!$('#sidebar').classList.contains('open');$('#sidebar').classList.toggle('open',open);$('#backdrop').classList.toggle('show',open);$('#menu-toggle').setAttribute('aria-expanded',String(open));});$('#backdrop').addEventListener('click',closeMenu);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus();}if(e.key==='Escape')closeMenu();});
window.addEventListener('hashchange',route);route();
