const EXTRA_LABS={
 activation:{title:'激活函数与局部梯度',desc:'在同一个输入位置比较 sigmoid、tanh、ReLU 的输出与导数。',lesson:'03'},
 chainrule:{title:'链式法则：把梯度拆成三个因子',desc:'对一个两层标量网络做真实前向与解析反传，并用中心差分核对。',lesson:'03'},
 momentum:{title:'二维优化：狭长谷里的动量',desc:'在 L(x,y)=½(x²+10y²) 上比较 SGD 与动量的参数轨迹。',lesson:'06'},
 dropout:{title:'Dropout：单次结果与期望',desc:'观察随机保留、倒置缩放与多次采样均值的区别。',lesson:'05'},
 normalization:{title:'BatchNorm 与 LayerNorm 的统计轴',desc:'只缩放一个样本，观察它如何影响另一个样本的归一化输出。',lesson:'05'},
 bptt:{title:'时间链上的梯度消失与爆炸',desc:'逐步相乘局部导数，观察长度、局部增益与裁剪阈值的作用。',lesson:'07'},
 nms:{title:'NMS：谁抑制了谁？',desc:'对固定的四个同类框执行真实贪心 NMS，查看选择过程。',lesson:'12'},
 curves:{title:'本机真实训练曲线对照',desc:'读取已运行的 CPU 多种子对照结果，按 epoch、step 或墙钟时间比较。',lesson:'15'},
 lora:{title:'LoRA：低秩更新节省了什么？',desc:'调节 rank，比较单个线性层的全量参数与 LoRA 可训练参数。',lesson:'08'}
};
function extraControls(kind){
 if(kind==='activation')return range('x','输入 x',-6,6,1,.1)+select('fn','激活函数',[[0,'sigmoid'],[1,'tanh'],[2,'ReLU']]);
 if(kind==='chainrule')return range('w','输入权重 w',-3,3,.8,.1)+range('v','输出权重 v',-3,3,1.2,.1)+range('x','输入 x',-3,3,1,.1);
 if(kind==='momentum')return range('eta','学习率 η',.01,.3,.08,.01)+range('beta','动量 β',0,.95,.8,.05);
 if(kind==='dropout')return range('p','丢弃概率 p',0,.9,.5,.1)+range('samples','独立采样次数',1,500,50)+range('seed','随机种子',1,100,7);
 if(kind==='normalization')return range('scale','第二个样本的缩放倍数',.2,5,1,.1);
 if(kind==='bptt')return range('factor','每步局部导数（标量简化）',.1,1.6,.9,.05)+range('steps','时间步数 T',1,80,20)+range('clip','最终梯度裁剪阈值',.5,10,2,.5);
 if(kind==='nms')return range('threshold','抑制阈值（IoU > threshold）',0,1,.5,.05);
 if(kind==='curves')return select('seed','随机种子',(EXPERIMENT?.settings.seeds||[7]).map(s=>[s,String(s)]))+select('axis','横轴',[[0,'optimizer step'],[1,'epoch'],[2,'墙钟时间（含评价）']])+select('metric','纵轴',[[0,'训练 loss'],[1,'验证 loss'],[2,'验证 accuracy'],[3,'平均梯度范数']]);
 if(kind==='lora')return range('rank','LoRA rank r',1,128,8)+select('dim','正方形线性层维度 d',[[512,'512'],[1024,'1024'],[4096,'4096']]);
 return '';
}
const palette=['#6853ce','#287a9a','#ad6341','#488852','#a6498b'];
function plotSeries(series,{xmin=0,xmax=1,ymin=0,ymax=1,xlabel='x',ylabel='y'}={}){
 const px=x=>55+430*(x-xmin)/(xmax-xmin||1),py=y=>235-195*(Math.max(ymin,Math.min(ymax,y))-ymin)/(ymax-ymin||1);
 return `<svg viewBox="0 0 540 290" role="img" aria-label="${esc(ylabel)} 随 ${esc(xlabel)} 的变化"><line class="graph-axis" x1="55" y1="235" x2="490" y2="235"/><line class="graph-axis" x1="55" y1="35" x2="55" y2="235"/><text class="chart-label" x="8" y="20">${esc(ylabel)}</text><text class="chart-label" x="4" y="45">${ymax.toFixed(2)}</text><text class="chart-label" x="4" y="238">${ymin.toFixed(2)}</text><text class="chart-label" x="48" y="255">${xmin.toFixed(1)}</text><text class="chart-label" x="450" y="255">${xmax.toFixed(1)}</text><text class="chart-label" x="220" y="279">${esc(xlabel)}</text>${series.map((s,i)=>`<polyline points="${s.points.map(([x,y])=>`${px(x).toFixed(2)},${py(y).toFixed(2)}`).join(' ')}" fill="none" stroke="${palette[i%palette.length]}" stroke-width="2"/>`).join('')}</svg><div class="plot-legend">${series.map((s,i)=>`<span><i style="background:${palette[i%palette.length]}"></i>${esc(s.name)}</span>`).join('')}</div>`;
}
function seeded(seed){return()=>{seed=(1664525*seed+1013904223)>>>0;return(seed+1)/4294967297;};}
function iouBoxes(a,b){const w=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0])),h=Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1])),inter=w*h;return inter/((a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-inter);}
function nmsToy(threshold){const boxes=[[25,25,115,105],[32,29,122,109],[105,30,195,110],[160,100,245,180]],scores=[.95,.9,.85,.7],pending=[0,1,2,3],keep=[],suppressed={};while(pending.length){const i=pending.shift();keep.push(i);for(let n=pending.length-1;n>=0;n--){const j=pending[n],overlap=iouBoxes(boxes[i],boxes[j]);if(overlap>threshold){suppressed[j]={by:i,iou:overlap};pending.splice(n,1);}}}return {boxes,scores,keep,suppressed};}
function updateExtraLab(el,kind,p){const visual=el.querySelector('.lab-visual'),result=el.querySelector('.lab-result');let html='',out='';
 if(kind==='activation'){const fs=[x=>1/(1+Math.exp(-x)),Math.tanh,x=>Math.max(0,x)],ds=[x=>{const s=fs[0](x);return s*(1-s);},x=>1-Math.tanh(x)**2,x=>x>0?1:0],xs=Array.from({length:121},(_,i)=>-6+i*.1),f=fs[p.fn],d=ds[p.fn];html=plotSeries([{name:'函数值',points:xs.map(x=>[x,f(x)])},{name:'局部导数',points:xs.map(x=>[x,d(x)])}],{xmin:-6,xmax:6,ymin:-1.1,ymax:p.fn===2?6:1.1,xlabel:'输入 x',ylabel:'函数值 / 导数'});out=`x=${p.x.toFixed(1)}，f(x)=${f(p.x).toFixed(5)}，f′(x)=${d(p.x).toFixed(5)}。${p.fn===2?'ReLU 在 0 不可导，此处采用框架常见的导数 0 约定。':'在饱和区域，导数接近 0；多层相乘可能进一步衰减。'}<br>曲线展示整个区间，滑块显示当前点的数值，不能把“导数小”直接等同于模型一定无法训练。`;}
 if(kind==='chainrule'){const{x,w,v}=p,target=1,h=Math.tanh(w*x),pred=v*h,res=pred-target,loss=.5*res**2,g=res*v*(1-h*h)*x,eps=1e-5,L=ww=>.5*(v*Math.tanh(ww*x)-target)**2,numeric=(L(w+eps)-L(w-eps))/(2*eps);html=`<div class="flow"><span>x=${x.toFixed(1)}</span><i>→ ×w</i><span>a=${(w*x).toFixed(3)}</span><i>→ tanh</i><span>h=${h.toFixed(3)}</span><i>→ ×v</i><span>ŷ=${pred.toFixed(3)}</span><i>→ loss</i><span>${loss.toFixed(4)}</span></div>`;out=`目标 y=1；L=½(ŷ−y)²。<br>∂L/∂w=(ŷ−y) × v × (1−h²) × x<br>= ${res.toFixed(4)} × ${v.toFixed(1)} × ${(1-h*h).toFixed(4)} × ${x.toFixed(1)} = <strong>${g.toFixed(6)}</strong><br>中心差分=${numeric.toFixed(6)}；绝对误差=${Math.abs(g-numeric).toExponential(2)}。放大 |wx| 会让 tanh 饱和。`;}
 if(kind==='momentum'){const run=beta=>{let x=3,y=3,vx=0,vy=0;const points=[[x,y]];for(let t=0;t<45;t++){vx=beta*vx+x;vy=beta*vy+10*y;x-=p.eta*vx;y-=p.eta*vy;points.push([x,y]);}return points;};const a=run(0),b=run(p.beta),cap=4;html=plotSeries([{name:'SGD',points:a},{name:`Momentum β=${p.beta.toFixed(2)}`,points:b}],{xmin:-cap,xmax:cap,ymin:-cap,ymax:cap,xlabel:'参数 x（横坐标不按时间单调）',ylabel:'参数 y'});const last=b.at(-1);out=`η=${p.eta.toFixed(2)}，β=${p.beta.toFixed(2)}；45 步动量末端 L=${(.5*(last[0]**2+10*last[1]**2)).toExponential(3)}。<br>v=βv+g，θ←θ−ηv；起点 (3,3)，最优点 (0,0)。超出图框 ±4 的轨迹已按显示范围截断/裁出，数值仍是真实迭代。动量也可能震荡或发散，不能仅因路径更平滑就判断更优。`;}
 if(kind==='dropout'){const rng=seeded(p.seed),x=[1,2,3,4,5,6,7,8],sums=Array(8).fill(0);let first;for(let j=0;j<p.samples;j++){const row=x.map(v=>rng()<p.p?0:v/(1-p.p));if(!j)first=row;row.forEach((v,i)=>sums[i]+=v);}const means=sums.map(v=>v/p.samples);html=`<div class="matrix-label">原输入</div>${matrix(x,8)}<div class="matrix-label">第一次随机输出</div>${matrix(first,8,i=>first[i]!==0)}<div class="matrix-label">${p.samples} 次采样的平均输出</div>${matrix(means,8)}`;out=`p=${p.p.toFixed(1)}；保留值乘 1/(1−p)=${(1/(1-p.p)).toFixed(2)}。<br>理论期望等于原输入；有限样本均值会波动。当前最大均值误差=${Math.max(...means.map((v,i)=>Math.abs(v-x[i]))).toFixed(3)}。这里生成固定种子的独立随机 mask，评估模式应直接返回原输入。`;}
 if(kind==='normalization'){const x=[[1,2,4],[2*p.scale,6*p.scale,8*p.scale]],norm=arr=>{const m=arr.reduce((a,b)=>a+b,0)/arr.length,v=arr.reduce((s,a)=>s+(a-m)**2,0)/arr.length;return arr.map(a=>(a-m)/Math.sqrt(v+1e-5));},bn=[[],[]];for(let c=0;c<3;c++){const ys=norm([x[0][c],x[1][c]]);bn[0][c]=ys[0];bn[1][c]=ys[1];}const ln=x.map(norm);html=`<div class="matrix-label">输入 [B=2,D=3]；第二行 × ${p.scale.toFixed(1)}</div>${matrix(x.flat(),3)}<div class="matrix-label">BN：每列跨 batch（训练批统计）</div>${matrix(bn.flat(),3)}<div class="matrix-label">LN：每行跨 feature</div>${matrix(ln.flat(),3)}`;out=`第二行缩放=${p.scale.toFixed(1)}。LN 第一行只依赖该行，改变第二行不会影响第一行。BN 第一行会受第二行影响。<br>γ=1、β=0、ε=10⁻⁵；方差使用当前统计轴的总体方差。仅展示训练期规范化，不模拟 running_mean/var 或 BN 推理行为。B=2 时 BN 数值常接近 ±1，随相对大小反转。`;}
 if(kind==='bptt'){const points=Array.from({length:p.steps+1},(_,t)=>[t,t*Math.log10(p.factor)]),grad=p.factor**p.steps,clipped=Math.min(grad,p.clip);html=plotSeries([{name:'log₁₀ |梯度乘积|',points}],{xmin:0,xmax:p.steps,ymin:Math.min(-1,points.at(-1)[1]),ymax:Math.max(1,points.at(-1)[1]),xlabel:'链条长度 T',ylabel:'log₁₀ |gradient|'});out=`局部导数=${p.factor.toFixed(2)}，T=${p.steps}，原梯度=${grad.toExponential(4)}；最终阈值裁剪后=${clipped.toExponential(4)}。<br>只在最终乘积上做标量幅度裁剪；不会把消失的梯度放大回来。真实 RNN 是随时间变化的 Jacobian 矩阵乘积，本图不等价于完整 LSTM 模型。`;}
 if(kind==='nms'){const r=nmsToy(p.threshold);html=`<svg viewBox="0 0 275 215" role="img" aria-label="NMS 选择的候选框">${r.boxes.map((b,i)=>`<rect x="${b[0]}" y="${b[1]}" width="${b[2]-b[0]}" height="${b[3]-b[1]}" fill="${palette[i]}" fill-opacity="${r.keep.includes(i)?.14:.02}" stroke="${palette[i]}" stroke-width="${r.keep.includes(i)?3:1}" ${r.keep.includes(i)?'':'stroke-dasharray="5 4"'}/><text x="${b[0]+5}" y="${b[1]+14}" fill="${palette[i]}" font-size="11">${'ABCD'[i]} ${r.scores[i]}</text>`).join('')}</svg>`;out=`阈值=${p.threshold.toFixed(2)}；粗实线=保留，虚线=抑制。<br>保留顺序：${r.keep.map(i=>'ABCD'[i]).join(' → ')}<br>${Object.entries(r.suppressed).map(([i,s])=>`${'ABCD'[i]} 被 ${'ABCD'[s.by]} 抑制，IoU=${s.iou.toFixed(3)}`).join('<br>')||'没有候选被抑制。'}<br>同一类别，按固定分数从高到低贪心选择；这不是评价时的 TP/FP 匹配。`;}
 if(kind==='curves'){
  if(!EXPERIMENT){html='<p>暂无已运行实验数据，请先运行 Code/experiments/optimizer_study.py，再构建页面。</p>';out='未加载数据，不生成虚构曲线。';}
  else{const xkey=['step','epoch','wall_seconds'][p.axis],ykey=['train_loss','val_loss','val_acc','grad_norm_mean'][p.metric],configs=EXPERIMENT.summary.map(s=>s.config),series=configs.map(name=>({name,points:EXPERIMENT.curves.filter(r=>r.config===name&&r.seed===p.seed&&(p.metric!==3||r.epoch>0)).map(r=>[r[xkey],r[ykey]])})),ys=series.flatMap(s=>s.points.map(p=>p[1])),xs=series.flatMap(s=>s.points.map(p=>p[0]));html=plotSeries(series,{xmin:0,xmax:Math.max(...xs),ymin:0,ymax:p.metric===2?1:Math.max(...ys)*1.05,xlabel:xkey,ylabel:ykey});out=`真实 CPU 运行：${esc(EXPERIMENT.generated_at)} · seed=${p.seed} · ${EXPERIMENT.settings.epochs} epochs<br>同一 seed 的初始化和 batch 顺序配对；数据划分固定。没有为不同优化器做等预算全面调参。<br>墙钟时间含评价，训练计时含梯度统计；此小任务的亚秒级测时受 CPU 负载及执行顺序影响，不可当硬件速度基准。<br><a href="#evidence">查看多种子汇总与证据路径 →</a>`;}
 }
 if(kind==='lora'){const d=p.dim,r=p.rank,full=d*d,low=r*(2*d);html=`<div class="flow"><span>x:[…,${d}]</span><i>→</i><span>冻结 W:[${d},${d}]</span><i>+</i><span>A:[${r},${d}] → B:[${d},${r}]</span></div><div class="bar-row"><span>全量</span><div class="bar-track"><div class="bar-fill" style="width:100%"></div></div><span>100%</span></div><div class="bar-row"><span>LoRA</span><div class="bar-track"><div class="bar-fill target" style="width:${low/full*100}%"></div></div><span>${(low/full*100).toFixed(2)}%</span></div>`;out=`ΔW=(α/r)BA；r=${r}，W 原参数=${full.toLocaleString()}；LoRA 新增可训练参数=${low.toLocaleString()}。<br>只计算一个无偏置线性层的矩阵参数，不代表整模型比例。冻结基座仍需加载权重、前向与相关反向计算，<strong>可训练参数减少不等于总显存同比下降</strong>。质量与 rank 的关系需要实验验证。`;}
 visual.innerHTML=html;result.innerHTML=out;
}
function depthHTML(l,open=false){const d=l.depth;if(!d)return '';return `<section class="panel depth-panel"><div class="eyebrow">DERIVE → IMPLEMENT → VERIFY</div><h2>${esc(d.title)}</h2><p class="subtle">约定：${esc(d.assumption)}</p><details ${open?'open':''}><summary>展开逐步推导（${d.steps.length} 步）</summary><ol class="task-list">${d.steps.map(([t,b])=>`<li><strong>${esc(t)}</strong><br>${esc(b)}</li>`).join('')}</ol></details><details ${open?'open':''}><summary>对应的 PyTorch 知识与实现片段</summary><p>${esc(d.torch)}</p><pre class="code-block"><code>${esc(d.code)}</code></pre><p class="subtle">标注“已定义”的变量由所在训练流程提供；这是聚焦机制的片段，不是每段都能脱离上下文独立运行。</p></details><div class="callout"><strong>用什么证据验证？</strong>${esc(d.verify)}</div></section>`;}
function depthPage(id){const l=lessonById(id)||lessonById('03');return header('MATHEMATICS MEETS PYTORCH','推导与框架实现','不必推导每篇模型论文，但核心损失、链式法则、参数共享和张量轴需要真正走通。')+`<nav class="filters depth-nav" aria-label="推导模块">${COURSE.map(m=>`<a class="btn small ${l.id===m.id?'primary':''}" href="#depth/${m.id}">${m.id} ${esc(m.en.split(',')[0])}</a>`).join('')}</nav><h2>${l.id} · ${esc(l.title)}</h2>${depthHTML(l,true)}<div class="lesson-footer"><a class="btn" href="#lesson/${l.id}">回到完整课程 →</a><a class="btn" href="#plan">查看 PyTorch 学习清单 →</a></div>`;}
function coveragePage(){return header('COVERAGE, NOT A FALSE COMPLETION RATE','课件覆盖与逐页索引','原 HTML 是主线导学，不是全部课件的替代品。这里区分已展开的核心、需要深读的拓展和工程补课。')+`<div class="callout warning"><strong>如何使用这个索引</strong>章节数量不能代表内容覆盖比例。课件包含重复讲解、图示、应用实例与研究拓展，不能把“15 个模块”换算成某个已掌握百分比。下方提供全部 ${SOURCE_PAGES.length} 份主课件的 ${SOURCE_PAGES.reduce((n,d)=>n+d.pages.length,0)} 页入口；抽取的标题可能缺字，页面编号以 PDF 为准。</div><div class="resources-grid"><section class="panel"><h3>本站已展开</h3><p class="subtle">训练与泛化、MLP/CE/反传、CNN、残差与优化、RNN、attention、ViT、GAN、前向 diffusion、检测分割、图像梯度、实验设计。新增 15 组分步推导和 PyTorch 片段。</p></section><section class="panel"><h3>课件里有，本站尚未同等展开</h3><p class="subtle">SVM/PCA 等 ML 回顾；自监督、对比学习与迁移学习；各 CNN 架构细节；完整 LSTM 门反传；GAN 各变体；完整 DDPM/ELBO 与采样器；LoRA/DreamBooth/ControlNet；检测器和分割器的具体实现。先掌握核心，再按目标选择深读。</p></section></div>${SOURCE_PAGES.map(d=>`<details class="walkthrough"><summary>${esc(d.path.split('/').at(-1))} · ${d.pages.length} 页</summary><p>逐页索引来自本地 PDF 文本；这里只提供阅读定位，不把列出标题当作已讲解。</p><div class="page-links">${d.pages.map(p=>`<a href="${esc(uri({path:d.path,page:p.page}))}" target="_blank" rel="noopener"><b>${p.page}</b> ${esc(p.title||'图示 / 无可提取标题')}</a>`).join('')}</div></details>`).join('')}<a class="btn primary" href="#plan">查看课程以外的补课路线 →</a>`;}
function evidencePage(){if(!EXPERIMENT)return header('EXPERIMENT EVIDENCE','尚无真实运行结果','先运行 Code 中的实验，再构建页面。');return header('REAL RUNS · LIMITED CLAIMS','把真实实验变成可核验的理解','以下是助手在本机执行的教学基线。你需要亲自复现、修改并解释之后，才能讲成自己的经验。')+`<div class="statusline">CPU · ${esc(EXPERIMENT.environment.torch)} · ${EXPERIMENT.runs.length} 次训练 · ${EXPERIMENT.settings.seeds.length} 个种子 · 每次 ${EXPERIMENT.settings.epochs} epochs</div>${labHTML('curves')}<div class="table-wrap"><table class="data-table"><thead><tr><th>配置</th><th>末轮验证 accuracy 均值 ± 样本标准差</th><th>曾达到 90%</th><th>平均墙钟时间</th></tr></thead><tbody>${EXPERIMENT.summary.map(r=>`<tr><td>${esc(r.config)}</td><td>${(r.val_acc_mean*100).toFixed(2)}% ± ${(r.val_acc_sample_std*100).toFixed(2)} 个百分点</td><td>${r.threshold_hits}/${r.runs}</td><td>${r.wall_seconds_mean.toFixed(3)} s</td></tr>`).join('')}</tbody></table></div><div class="callout warning"><strong>这组结果能说什么，不能说什么</strong>只能说明这些固定设置在该合成数据与种子上的表现。不是 LLM 经验，也不是“Adam 总是更好”的证据。首次达到阈值不保证末轮仍然保持；按验证曲线检查稳定性。CPU 亚秒级测时不能推广到 GPU 加速收益。</div><section class="panel"><h3>下一次由你完成的实验</h3><ol class="task-list"><li>先复现基线，解释为什么较大学习率可能先达到阈值又退步。</li><li>只改变 batch、数据噪声或网络宽度中的一项，开新的结果目录。</li><li>比较 step、time、验证表现和梯度范数，不只看训练 loss。</li><li>记录你排查过的一个失败例子与修复前后证据。</li></ol><p class="subtle">固定下一 batch 的 checkpoint 恢复误差：${EXPERIMENT.resume_check.next_update_max_abs_error}。只验证确定性 CPU 情形，不涵盖 Dropout/随机 DataLoader 的完整恢复。</p><div class="storage-controls"><a class="btn" href="../Code/experiments/optimizer_study.py" download>实验脚本 ↓</a><a class="btn" href="../Code/experiments/README.md" target="_blank">运行与解释说明 ↗</a><a class="btn" href="${esc('../Code/'+EXPERIMENT_PATH)}" download>完整配置、曲线与报告 ↓</a></div></section>`+footer();}
function planPage(){return header('A CPU-FIRST PLAN · 100–200 RMB GPU CAP','算法基础 → 小模型 → 有评测的微调','方向：通用算法基础 + 大模型应用/微调。预算是试验上限，不是必须花掉的钱。')+`
<section class="panel"><h2>Code 文件夹如何练</h2><div class="table-wrap"><table class="data-table"><tr><th>层次</th><th>做什么</th><th>验证</th></tr><tr><td>手写核心</td><td>回归、softmax/CE、MLP 反传、优化器、单步 RNN、attention、IoU/NMS</td><td>小输入 → 数值梯度 / 框架对照</td></tr><tr><td>框架实现</td><td>小 CNN、残差、LSTM、小 Transformer、简单 GAN/DDPM</td><td>形状、梯度、小样本过拟合、验证集</td></tr><tr><td>预训练适配</td><td>小规模 LoRA、任务评测、失败样本与成本比较</td><td>基座与微调对照、同一评测集、多配置</td></tr></table></div><p class="subtle">现有 LSA 脚本是 sklearn 应用；不必手写 SVD 求解器或 CUDA 卷积。<a href="../Code/README.md" target="_blank">Code 使用说明 ↗</a></p></section>
<div class="section-head"><h2>先补 PyTorch 的八项基本功</h2></div><div class="cards">${[['张量与形状','dtype/device、广播、切片、reshape/transpose、连续内存。'],['自动微分','叶子张量、grad 累加、detach、no_grad、局部/全局计算图。'],['模块与状态','nn.Module、Parameter、buffer、train/eval、state_dict。'],['数据管线','Dataset、DataLoader、collate、padding、mask、划分与数据泄漏。'],['训练循环','logits 与 loss、清梯度、backward、step、scheduler、梯度裁剪。'],['验证与复现','独立验证、种子、配置、batch 顺序、错误标签与失败样本。'],['保存与恢复','model/optimizer/scheduler/scaler、随机状态和采样器位置。'],['资源与性能','计时、CPU/GPU 利用率、AMP、梯度累积、activation checkpointing；后面三项按实际硬件需要补。']].map(([t,d])=>`<article class="module-card"><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>
<div class="section-head"><h2>四个可检验的阶段</h2></div><section class="panel"><ol class="task-list"><li><strong>本机基础：</strong>手写 MLP/attention 并做梯度对照；完成当前优化器实验。产物：解析推导、代码、CSV、一次失败诊断。</li><li><strong>CPU 小语言模型：</strong>用小语料训练小字符/token 级 causal Transformer，理解 tokenizer、shifted labels、padding loss mask、perplexity 与自回归生成。目标是机制，不能把随机小模型包装成有用的大模型。</li><li><strong>租卡前准备：</strong>固定一个可量化任务、验证/测试划分、base model 版本和数据；在 CPU 跑通预处理及少量 batch，估计模型、梯度、优化器、激活的显存。模型大小最终由任务和显存决定，不现在承诺某个大模型一定能装下。</li><li><strong>有限 GPU 对照：</strong>以 0.5B–1.5B 量级的候选预训练模型作为待验证起点，做基座/少样本提示/LoRA 对照。选择 1–2 个主要变量，例如 rank 或学习率；报告任务指标、耗时、峰值显存、失败样本与预算。是否可行需先短测。</li></ol></section>
<div class="section-head"><h2>100–200 元怎样花得可控</h2></div><section class="panel"><p>建议按总预算划分：10% 短测与显存验证，60% 核心对照，20% 复测与评价，10% 余量。先检查任务是否值得租卡，再购买按量实例。</p><p class="subtle">示例算术，不是当前报价：若实例 2 元/小时，总预算 200 元，预留 20 元其他费用与余量，则理论实例开机上限为 90 小时；这不是建议跑满 90 小时。100 元在相同假设下是 40 小时。实际单价、可用卡、存储与税费以平台当时页面为准。</p><ol class="task-list"><li>先用 5–10 分钟短测估计每个实验耗时和峰值内存，剩余训练按测量估算。</li><li>准备代码、下载/预处理数据、写报告尽量在本机完成；不要让 GPU 等人。</li><li>脚本设置最大 steps/时长并保存 checkpoint；另配置实例自动关机并核对计费停止。结束进程、关浏览器和停止实例不是同一回事。</li><li>保留必要日志和权重到本地。停止实例后检查付费磁盘/存储是否还在计费。</li></ol><p class="subtle">已查官方资料（2026-10-05）：<a href="https://research.google.com/colaboratory/faq.html" target="_blank" rel="noopener">Colab FAQ</a> 说明免费资源不保证，限制会变；<a href="https://www.autodl.com/docs/price/" target="_blank" rel="noopener">AutoDL 计费</a> 以实例开关机时长计费，付费盘另算；<a href="https://docs.runpod.io/pods/pricing" target="_blank" rel="noopener">Runpod 计费</a> 需区分计算与存储。这里没有开通、租用或付费。</p></section>
<div class="section-head"><h2>这门课之外还要补什么</h2></div><div class="table-wrap"><table class="data-table"><tr><th>补充方向</th><th>必须做出的证据</th><th>优先级</th></tr><tr><td>训练工程与排错</td><td>数据检查、小样本过拟合、NaN/梯度诊断、checkpoint 恢复</td><td>现在</td></tr><tr><td>实验设计与评价</td><td>无泄漏划分、基线、消融、多种子、预先定义指标与失败分析</td><td>现在</td></tr><tr><td>NLP/LLM 训练链</td><td>tokenizer、next-token loss、mask、采样、上下文与 KV cache 的解释</td><td>attention 后</td></tr><tr><td>LoRA/SFT 与数据质量</td><td>训练目标、可训练参数、rank 对照、过拟合与固定任务评测</td><td>小模型后</td></tr><tr><td>应用检索与可靠评测</td><td>若做 RAG，区分检索失败与生成失败；加入引用、拒答和错误案例</td><td>按岗位项目选</td></tr><tr><td>部署性能</td><td>延迟/吞吐、内存、量化误差与成本；从单机开始</td><td>核心链条跑通后</td></tr></table></div><p class="subtle">这是面向你的目标补充的路线，不等于老师完全没有提过这些内容。材料搜索只能定位显式出现的文字，不能证明课堂从未讲过。</p>
<section class="panel"><h3>少而精的官方资料</h3><div class="external-list"><a href="https://docs.pytorch.org/tutorials/beginner/basics/intro.html" target="_blank" rel="noopener">PyTorch Learn the Basics：按数据→模型→autograd→优化→保存补齐框架</a><a href="https://cs231n.stanford.edu/2025/assignments.html" target="_blank" rel="noopener">CS231n 作业：用实现和验证练基础，不只看模型名字</a><a href="https://huggingface.co/learn/llm-course/en/chapter7/1" target="_blank" rel="noopener">Hugging Face LLM Course：任务与语言模型训练</a><a href="https://huggingface.co/docs/peft/en/package_reference/lora" target="_blank" rel="noopener">PEFT LoRA：rank、target modules 与适配配置</a><a href="https://docs.pytorch.org/tutorials/beginner/saving_loading_models.html" target="_blank" rel="noopener">PyTorch checkpoint：区分推理权重与恢复训练</a></div><p class="subtle">先用本地课程建立知识主线；联网用来核验接口、硬件兼容性、计费和补足目标能力，不要同时开十门课。</p></section>`+footer();}
